id: DE6C4505E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:47:31+00:00'
last_modified: '2022-05-26T11:56:36.278342+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f94d:
      image_group_id: I1PD95879
      title: མི་འཁྲུགས་པའི་སྒྲུབ་ཐབས།
      total_pages: 1734
      order: 34
      base_file: f94d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
