id: ab3c2a3e20ad4220bfb0e983b9fbb919
initial_creation_type: ocr
source_metadata:
  volumes:
    c525f0b0f78e4b7c93c392e1e88b2c62:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: མི་འཁྲུགས་པའི་སྒྲུབ་ཐབས།
      total_pages: 1734
      volume_number: 34
